### ISSUE TITLE
Works with QNAP TS-h886 & Unraid 6.12.3

### ISSUE THREAD

**Issue by teffi71** [Stonyx/QNAP-EC#13]
No issue - just letting you know it works just fine ;)

<img width="534" alt="Screenshot 2023-08-17 at 17 41 20" src="https://github.com/Stonyx/QNAP-EC/assets/139787977/6a19b066-8bc7-40c0-8bff-8de54e01f1de">

**Comment by ich777** [comment]
Thanks, add that to the list in the Unraid plugin.

I hope that @Stonyx is alright, haven't heard of him in a while...

**Comment by ich777** [comment]
@teffi71 please close this issue, I'll add it to the list in Unraid.
