### ISSUE TITLE
TS-EC879U Support

### ISSUE THREAD

**Issue by znelbok** [Stonyx/QNAP-EC#16]
Is there any chance that this will support the TS-EC879U NAS from QNAP.

Its a rack mount 8 bay device.

**Comment by iooner** [comment]
Would be great ! I've the ts-ec1280u

**Comment by ich777** [comment]
Have both of you yet tried to load the module with:
`modprobe qnap-ec check-for-chip=no`

**Comment by iooner** [comment]
Will give a try !
