### ISSUE TITLE
Working with TVS-h674

### ISSUE THREAD

**Issue by shanelord01** [Stonyx/QNAP-EC#17]
Just wanted to let you know by issuing the below commands, this plugin works fine with the QNAP TVS-h674 (and likely the h874). Running UNRAID 6.12.8
```

mkdir -p /boot/config/modprobe.d
echo "options qnap-ec check-for-chip=no" > /boot/config/modprobe.d/qnap-ec.config
modprobe qnap-ec check-for-chip=no
```

Thanks.

**Comment by shanelord01** [comment]
Actually had to remove /boot/config/modprobe.d/qnap-ec.config and recreate it, then add the line 
`options qnap-ec check-for-chip=no` at the top.

**Comment by ich777** [comment]
I'm currently working on a implementation so that this is not needed anymore on Unraid.

**Comment by ich777** [comment]
@shanelord01 please try [this](https://forums.unraid.net/topic/92865-support-ich777-amd-vendor-reset-coraltpu-hpsahba/?do=findComment&comment=1410466) (please make sure that you are on Unraid 6.12.10).

**Comment by ich777** [comment]
If this is working for you please close this issue, I already issued a PR for that and will compile it from [my repository](https://github.com/ich777/QNAP-EC) in the meantime.
