### ISSUE TITLE
Debian 12  Makefile fails

### ISSUE THREAD

**Issue by TheSilverSadist** [Stonyx/QNAP-EC#20]
root@midgard:/home/MYUSERNAME/QNAP-EC# sudo make package DEBIAN=yes DESTDIR=/lib/modules/6.1.0-21-amd64
rm -f qnap-ec
make -C /lib/modules/6.1.0-21-amd64/build M=/home/MYUSERNAME/QNAP-EC clean
make[1]: Entering directory '/usr/lib/modules/6.1.0-21-amd64/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.1.0-21-amd64/build'
make: *** [Makefile:74: clean] Error 2

**Comment by TheSilverSadist** [comment]
Same error with

root@midgard:/home/MYUSERNAME/QNAP-EC# sudo make install
rm -f qnap-ec
make -C /lib/modules/6.1.0-21-amd64/build M=/home/MYUSERNAME/QNAP-EC clean
make[1]: Entering directory '/usr/lib/modules/6.1.0-21-amd64/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.1.0-21-amd64/build'
make: *** [Makefile:74: clean] Error 2

**Comment by irishj** [comment]
Same issue here, but with Ubuntu running the 5.10.55 kernel.

```
root@ubntu-5:~/QNAP-EC# make install
rm -f qnap-ec
make -C /lib/modules/5.10.55-051055-generic/build M=/root/QNAP-EC clean
make[1]: Entering directory '/usr/lib/modules/5.10.55-051055-generic/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.10.55-051055-generic/build'
make: *** [Makefile:74: clean] Error 2
```

**Comment by steve3d** [comment]
you need to install `headers` package according to the kernel version. without the headers package, you simply can not build any kernel modules.

for example
```
linux-headers-amd64/stable-security 6.1.99-1 amd64
  Header files for Linux amd64 configuration (meta-package)
```
