### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by dchimeno** [Stonyx/QNAP-EC#3]
Is it possible to create a package for ubuntu in order to avoid install ``build-essential``?
I'm running a server and only need a compiler for this driver.
I can colaborate with a github action if that helps.

BTW, I'm running on a TS-453d on Ubuntu 22.04 and after install the driver

```bash
sensors

qnap_ec-isa-0000
Adapter: ISA adapter
fan1:         834 RPM
fan3:         830 RPM
fan33:        753 RPM
fan34:       5117 RPM
fan35:       12114 RPM
fan36:       1211 RPM
temp1:        +28.0°C
temp6:        +30.0°C
```

Now I need a way to set the values, but thats another story...
Thanks for this great code!

**Comment by Stonyx** [comment]
Unfortunately drivers need to be recompiled for each version of the kernel.  There's no such thing as a generic driver package for Ubuntu or Debian.  It would be a  different package for every single different kernel version that Ubuntu or Debian use.  My recommendation would be to create a VM of the server environment that runs the same OS and kernel version and compile it there.  Then simply move the files over to the production server.

**Comment by dchimeno** [comment]
I see, thanks for clarification.
I guess the final solution would be include to it in kernel tree, not sure if licenses are ok.
Thanks!
