### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by lowrents** [Stonyx/QNAP-EC#4]
actually you can close the issue directly; I just wanted to say: you saved my life! I really appreciate your work. This helps me running TrueNAS SCALE on my QNAP TS-453D. Currently I am a bit "reverting" my failed decision not going for a custom build. But so far everything is working great and your repo was the last pice of the puzzle. I was close before soldering some controller in like [this guy](https://www.truenas.com/community/threads/qnap-ts251-fan-100.93196/).

**Comment by Stonyx** [comment]
We're glad you found this driver helpful.  Thanks for the thanks.
