### ISSUE TITLE
Using QNAP TVS-471 for Unraid

### ISSUE THREAD

**Issue by gregzee** [Stonyx/QNAP-EC#8]
Hi,

I am unsure if this supports TVS-471, but I have since repurposed it for unraid. . Some quick googling yields no result on the IT8528 chip for the TVS-471. I am looking to get the QNAP fan function on unraid.

Diag report:
[server-diagnostics-20221231-1331.zip](https://github.com/Stonyx/QNAP-EC/files/10327946/server-diagnostics-20221231-1331.zip)

**Comment by Stonyx** [comment]
I personally haven't worked with that specific unit so I wouldn't know which hardware chip it actually uses.  There's three ways I can think of to figure out if you're running a supported chip on your NAS.  First, you could try contacting QNAP and asking them.  They might share this info but I doubt it.  Second, you could actually try using the QNAP-EC driver on your unit and see if it complains about not being able to find a compatible chip.  Third, there's actually a file located on the original QNAP OS firmware that describes the hardware via key value pairs.  One of those pairs is related to the embedded controller chip.  Unfortunately, I don't remember the name of that file or the key value pair at the moment but I do know it exists.  But if you've already switched the device over to Unraid that file is long gone.

**Comment by ich777** [comment]
@Stonyx looking at that issue I would recommend it due to no further response... :)

**Comment by gregzee** [comment]
> I personally haven't worked with that specific unit so I wouldn't know which hardware chip it actually uses. There's three ways I can think of to figure out if you're running a supported chip on your NAS. First, you could try contacting QNAP and asking them. They might share this info but I doubt it. Second, you could actually try using the QNAP-EC driver on your unit and see if it complains about not being able to find a compatible chip. Third, there's actually a file located on the original QNAP OS firmware that describes the hardware via key value pairs. One of those pairs is related to the embedded controller chip. Unfortunately, I don't remember the name of that file or the key value pair at the moment but I do know it exists. But if you've already switched the device over to Unraid that file is long gone.


I already switched on over to unraid and completely wiped QNAP OS. Fans are running but not dynamically. I actually did not see this response, I'll take a look into how I can scrape this information somehow, but like you mentioned... probably all gone.
